### ISSUE TITLE
Warning and deprecated alerts

### ISSUE THREAD

**Issue by bachvtuan** [AustinScola/mypy-cache-github-action#265]
![image](https://user-images.githubusercontent.com/2065400/201816685-d110cbe1-61dc-4bc9-ac38-d6f1567a24cb.png)

**Comment by ericbn** [comment]
The warnings are:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: AustinScola/mypy-cache-github-action@v1

> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by ericbn** [comment]
This GitHub Action does exactly the same as:

```
      - name: Cache mypy
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: mypy-cache-${{ github.sha }}
          restore-keys: mypy-cache-
```

The implementation could be refactored to be as simple as that (using actions/cache@v3 instead of reimplementing it).

**Comment by bachvtuan** [comment]
@ericbn I forked latest package from "https://github.com/actions/typescript-action to https://github.com/kajalagroup/code-QA-cache-github-action with same idea from this repository:
Usage:
```
  - name: Cache mypy
    uses: kajalagroup/code-QA-cache-github-action@v1.7
    with:
      path: .mypy_cache
      key: mypy-cache
      restore-keys: mypy-cache
```
They key "mypy-cache"  will be appended with {{github.sha}} automatically
